import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Oogiri Platform - Next.js</title>
        <meta name="description" content="Generated by Next.js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          お兄ちゃんの{' '}
          <a href="https://nextjs.org">Oogiri Platform!</a>
        </h1>

        <p>
          ここはNext.jsで動いてるぜ。Vercelへのデプロイ準備完了！
        </p>
      </main>
    </div>
  );
}
